version: 2
updates:
  - package-ecosystem: gomod
    directory: /api
    schedule:
      interval: weekly
    labels:
      - dependencies
      - go

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    labels:
      - dependencies
      - javascript

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci
