FROM nginx:1.29.0-alpine

COPY nginx.conf /etc/nginx/nginx.conf

ARG LOCKSMITH_APP_PORT

RUN sed -i -e 's/$LOCKSMITH_APP_PORT/'"$LOCKSMITH_APP_PORT"'/g' /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]